# Generated by Django 6.0.3 on 2026-04-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='類別')),
                ('name', models.CharField(max_length=255, verbose_name='品名')),
                ('price_detail', models.TextField(verbose_name='價格詳細')),
                ('date', models.CharField(max_length=50, verbose_name='日期')),
            ],
        ),
    ]
