# Generated by Django 6.0.3 on 2026-04-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.TextField(blank=True, default=''),
        ),
    ]
